spring:
  profiles:
    active: local
  application:
    name: {application-name}
  jackson:
    default-property-inclusion: NON_NULL
  resources:
    static-locations: classpath:/
  datasource:
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: {pool-name}
      schema: {schema}
  jpa:
    hibernate:
      ddl-auto: create
      # ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level: debug

---
server:
  port: 8085    # 포트 변경 필요
spring:
  profiles: local
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect

cors.allowed-domains:
#  - 192.168.123.456
---
server:
  port: 8085    # 포트 변경 필요
spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect

cors.allowed-domains:
#  - 192.168.123.456
---
server:
  port: 8085    # 포트 변경 필요
spring:
  profiles: prd
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect

cors.allowed-domains:
#  - 192.168.123.456
---