spring:
  profiles:
    active: local
  application:
    name: {application-name}
  jackson:
    default-property-inclusion: NON_NULL
  resources:
    static-locations: classpath:/
  datasource:
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 30
      minimum-idle: 3
      pool-name: {pool-name}
      schema: {schema}
  jpa:
    hibernate:
      ddl-auto: create
      # ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: {username}
    password: {password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: static/messages/messages
    encoding: UTF-8
    cache-duration: 5
    fallback-to-system-locale: false
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*-mapper.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    default-statement-timeout: 1000
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null
---
server:
  port: 9000    # 포트 변경 필요
spring:
  profiles: local
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    kr.co.kesti: debug

cors.allowed-domains:
#  - 192.168.123.456
---
server:
  port: 9000    # 포트 변경 필요
spring:
  profiles: dev
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    kr.co.kesti: info

cors.allowed-domains:
#  - 192.168.123.456
---
server:
  port: 9000    # 포트 변경 필요
spring:
  profiles: prd
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.OracleDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    kr.co.kesti: info

cors.allowed-domains:
#  - 192.168.123.456
---