spring:
  profiles:
    active: local
  resources:
    static-locations: classpath:/
  jpa:
    hibernate:
      ddl-auto: create
      # ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: {username}
    password: {password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level: debug

---
server:
  port: 9000    # 포트 변경 필요
spring:
  profiles: local
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}

cors.allowed-domains:
#  - 192.168.123.456
---
server:
  port: 9000    # 포트 변경 필요
spring:
  profiles: dev
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}

cors.allowed-domains:
#  - 192.168.123.456
---
server:
  port: 9000    # 포트 변경 필요
spring:
  profiles: prd
  datasource:
#    ==== MySQL ====
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{host}:{port=3306}/{database}?serverTimezone=UTC

#    ==== Oracle ====
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@{host}:{port=1521}:{database}

#    ==== PostgreSQL ====
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://{host}:{port=5432}/{database}

#    ==== H2 ====
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://{host}:{port=5435}/mem:{database}

#    ==== MS-SQL ====
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://{host}:{port=1433}/{database}
    username: {username}
    password: {password}

cors.allowed-domains:
#  - 192.168.123.456
---