server:
  port: 9000
spring:
  profiles:
    active: local
  application:
    name: BACKEND-BOILERPLATE
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: wlfkfgksek95+
    hikari:
      max-lifetime: 300000
      maximum-pool-size: 10
      minimum-idle: 3
      pool-name: BACKEND
      schema: test
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          time_zone: Asia/Seoul
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: jayur830@gmail.com
    password: fcjpcrnxcxndbpzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: messages/messages
    encoding: UTF-8
    cache-duration: 5
    fallback-to-system-locale: false
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*-mapper.xml

---
server:
  port: 9000
spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    kr.co.kesti: debug
cors:
  allowed-domains: http://localhost:8080
---
server:
  port: 9000
spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
logging:
  level:
    kr.co.kesti: info
cors:
  allowed-domains: http://{host}:{port}
---
server:
  port: 9000
spring:
  profiles: prd
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
logging:
  level:
    kr.co.kesti: info
cors:
  allowed-domains: http://{host}:{port}